version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - WRITER_DB
            - READER_DB
        networks: 
            - laravel

    WRITER_DB:
        image: 'percona:8.0'
        container_name: WRITER_DB
        restart: unless-stopped
        ports:
            - '4306:3306'
        env_file:
            - "src/.env"
        environment:
            MYSQL_DATABASE: WRITER_DB
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: write_db
        volumes:
            - ./mysql/master.cnf:/etc/my.cnf.d/repl.cnf
            - ./mysql/master.sql:/docker-entrypoint-initdb.d/start.sql
        networks:
            - laravel


    READER_DB:
        image: 'percona:8.0'
        container_name: READER_DB
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./mysql/slave.cnf:/etc/my.cnf.d/repl.cnf
            - ./mysql/slave.sql:/docker-entrypoint-initdb.d/start.sql
        depends_on:
            - WRITER_DB
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel